# Gradle settings
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8 --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Minecraft & NeoForge versions
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.15-beta
loader_version_range=[3,)

# Java version (JEP 447: statements before super())
java_version=25

# Mod metadata
mod_id=avaritia
mod_name=Avaritia
mod_version=1.0.0-alpha
mod_license=All Rights Reserved
mod_group_id=com.avaritia
