# Gradle settings
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8 --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Minecraft & NeoForge versions
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.73
neo_version_range=[26.1.2.73,)
loader_version_range=[3,)

# Java version (JEP 447: statements before super())
java_version=25

# Mod metadata
mod_id=avaritia
mod_name=Re-Avaritia
mod_loader=neoforge
mod_license=MIT
mod_version=1.4.1
mod_version_tag=release
mod_group_id=committee.nova.mods
mod_authors=cnlimiter, cu6, lying_ice, IAFEnvoy, Asek3, MikhailTapio, NadienDev
mod_description=Are you the type of modded Minecraft player that makes a beeline for the designated \"end game\" and then gives up on ever playing again once you get there? Do you wish there was a way to make the process take significantly longer? Do you love GregTech, but wish it weren't so short? Do you sit down on your chest full of Galgadorian Drills and wish there was a mod that didn't just hand things to you on a silver platter?\n\n \n\nThis might be the mod for you!
issue_tracker=https://github.com/Nova-Committee/Re-Avaritia/issues
